### ISSUE TITLE
train_loc doesn't exist in att_split of the proposed split

### ISSUE THREAD

**Issue by tiangarin** [akku1506/Feature-Generating-Networks-for-ZSL#5]
```train_loc = matcontent['train_loc'].squeeze() - 1``` in util.py
An error occur in this sentence. After examing, I find that train_loc doesn't exist in att_splits of the proposed split, but exist in standard split. How to solve this problem?

**Comment by linerhome** [comment]
I cannot find it . how do you deal with it ?
please tell me .thanks
